---
title: 'PredStats: Project 1'
author: "Alex Poplawski & Lauren Moylan"
date: "10/6/2026"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Lock5Data)
library(Metrics)
library(ModelMetrics)
library(ggplot2)
library(tidyverse)
library(mosaic)
library(janitor)
library(readr)
library(caret)
```

```{r}
library(usethis)
create_github_token()
```

```{r}
# Import using semicolon delimiter
StudentAchievement <- read_delim("student-mat.csv", delim = ";")

# Clean column names
StudentAchievement <- StudentAchievement %>%
  clean_names()

# Convert categorical variables to factors
StudentAchievement <- StudentAchievement %>%
  mutate(
    school = factor(school),
    sex = factor(sex),
    address = factor(address),
    famsize = factor(famsize),
    pstatus = factor(pstatus),
    mjob = factor(mjob),
    fjob = factor(fjob),
    reason = factor(reason),
    guardian = factor(guardian),
    schoolsup = factor(schoolsup),
    famsup = factor(famsup),
    paid = factor(paid),
    activities = factor(activities),
    nursery = factor(nursery),
    higher = factor(higher),
    internet = factor(internet),
    romantic = factor(romantic)
  )

# Convert grade columns to numeric
StudentAchievement <- StudentAchievement %>%
  mutate(
    g1 = as.numeric(g1),
    g2 = as.numeric(g2),
    g3 = as.numeric(g3)
  )

View(StudentAchievement)
```

```{r}
FacebookMetrics <- read_delim(
  "dataset_Facebook.csv",
  delim = ";",
  trim_ws = TRUE
) %>%
  clean_names() %>% 
  mutate(
    type = as.factor(type),
    category = as.factor(category),
    paid = as.factor(paid)
  ) %>%
  mutate(across(
    -c(type, category, paid),
    ~ suppressWarnings(as.numeric(.))
  ))

View(FacebookMetrics)

```


### Predicting G3 (Student Final Grade) using Reason, Failures, Absenses, Travel Time, and Study Time.
